"""
SigWaz Field Maps — Sigma field names → Wazuh decoder paths
Covers: Windows, Zeek, Auditd, SysmonForLinux, Linux, Apache, Nginx, IIS,
        SSH, PAM, AWS, Azure, GCP, Office365, Okta, GitHub, Kubernetes,
        DNS, Network, Firewall, ClamAV, OSQuery, Sudo
"""
from __future__ import annotations
from typing import Dict, Optional

# ---------------------------------------------------------------------------
# Main registry: product (lowercase) → {sigma_field: wazuh_path}
# ---------------------------------------------------------------------------
FIELD_MAPS: Dict[str, Dict[str, str]] = {

    # ── Windows (Sysmon + native Windows events via Wazuh win decoder) ────
    "windows": {
        "Accesses": "win.eventdata.accesses",
        "AccessList": "win.eventdata.accessList",
        "AccessMask": "win.eventdata.accessMask",
        "AccountName": "win.eventdata.targetUserName",
        "Action": "win.eventdata.action",
        "AllowedToDelegateTo": "win.eventdata.allowedToDelegateTo",
        "Application": "win.eventdata.application",
        "ApplicationPath": "win.eventdata.applicationPath",
        "AttributeLDAPDisplayName": "win.eventdata.attributeLDAPDisplayName",
        "AttributeValue": "win.eventdata.attributeValue",
        "AuditPolicyChanges": "win.evendata.auditPolicyChanges",
        "AuditSourceName": "win.eventdata.auditSourceName",
        "AuthenticationPackage": "win.eventdata.authenticationPackageName",
        "AuthenticationPackageName": "win.eventdata.authenticationPackageName",
        "CallTrace": "win.eventdata.callTrace",
        "Caption": "win.eventdata.caption",
        "Channel": "win.eventdata.channel",
        "ChildImage": "win.eventdata.image",
        "CommandLine": "win.eventdata.commandLine",
        "Company": "win.eventdata.company",
        "ComputerName": "win.system.computer",
        "ContextInfo": "win.system.contextInfo",
        "CurrentDirectory": "win.eventdata.currentDirectory",
        "Description": "win.eventdata.description",
        "DestAddress": "win.eventdata.destAddress",
        "Destination": "win.eventdata.destination",
        "DestinationHostname": "win.eventdata.destinationHostname",
        "DestinationIp": "win.eventdata.destinationIp",
        "DestinationIsIpv6": "win.eventdata.destinationIsIpv6",
        "DestinationPort": "win.eventdata.destinationPort",
        "DestPort": "win.eventdata.destinationPort",
        "Details": "win.eventdata.details",
        "DeviceClassName": "win.eventdata.deviceClassName",
        "DeviceDescription": "win.eventdata.deviceDescription",
        "DeviceName": "win.eventdata.deviceName",
        "EngineVersion": "win.eventdata.engineVersion",
        "EventID": "win.system.eventID",
        "EventType": "win.eventdata.eventType",
        "FailureCode": "win.eventdata.failureCode",
        "FileVersion": "win.eventdata.fileVersion",
        "FilterName": "win.evendata.filterName",
        "FilterOrigin": "win.eventdata.filterOrigin",
        "FolderPath": "win.eventdata.image",
        "GrantedAccess": "win.eventdata.grantedAccess",
        "Hash": "win.eventdata.hashes",
        "Hashes": "win.eventdata.hashes",
        "HostApplication": "win.eventdata.hostApplication",
        "HostName": "win.eventdata.hostName",
        "HostVersion": "win.eventdata.hostVersion",
        "Image": "win.eventdata.image",
        "ImageName": "win.evendata.imageName",
        "ImagePath": "win.eventdata.imagePath",
        "ImageLoaded": "win.eventdata.imageLoaded",
        "ImpHash": "win.eventdata.impHash",
        "ImpersonationLevel": "win.eventdata.impersonationLevel",
        "Initiated": "win.eventdata.initiated",
        "IntegrityLevel": "win.eventdata.integrityLevel",
        "IpAddress": "win.eventdata.ipAddress",
        "KeyLength": "win.eventdata.keyLength",
        "Keywords": "win.eventdata.keywords",
        "LayerRTID": "win.eventdata.layerRTID",
        "Level": "win.system.level",
        "LogonGuid": "win.eventdata.logonGuid",
        "LogonId": "win.eventdata.logonId",
        "LogonProcessName": "win.eventdata.logonProcessName",
        "LogonType": "win.eventdata.logonType",
        "md5": "win.eventdata.hashes",
        "Message": "win.system.message",
        "ModifyingApplication": "win.system.modifyingApplication",
        "NewName": "win.eventdata.newName",
        "NewTargetUserName": "win.evendata.newTargetUserName",
        "NewUacValue": "win.eventdata.newUacValue",
        "NewValue": "win.eventdata.newValue",
        "ObjectClass": "win.eventdata.objectClass",
        "ObjectName": "win.eventdata.objectName",
        "ObjectServer": "win.eventdata.objectServer",
        "ObjectType": "win.eventdata.objectType",
        "ObjectValueName": "win.eventdata.objectValueName",
        "OldUacValue": "win.eventdata.oldUacValue",
        "Origin": "win.eventdata.origin",
        "OriginalFileName": "win.eventdata.originalFileName",
        "PackageName": "win.eventdata.packageName",
        "Param1": "win.evendata.param1",
        "Param2": "win.evendata.param2",
        "Param3": "win.evendata.param3",
        "Param4": "win.evendata.Param4",
        "Param5": "win.evendata.param5",
        "Param6": "win.evendata.param6",
        "Param7": "win.evendata.param7",
        "Param8": "win.evendata.Param8",
        "Param9": "win.evendata.Param9",
        "Param10": "win.evendata.Param10",
        "ParentCommandLine": "win.eventdata.parentCommandLine",
        "ParentImage": "win.eventdata.parentImage",
        "ParentIntegrityLevel": "win.eventdata.parentIntegrityLevel",
        "ParentProcessGuid": "win.eventdata.parentProcessGuid",
        "ParentUser": "win.eventdata.parentUser",
        "Payload": "win.eventdata.payload",
        "PipeName": "win.eventdata.pipeName",
        "PrivilegeList": "win.eventdata.privilegeList",
        "ProcessCommandLine": "win.eventdata.commandLine",
        "ProcessID": "win.eventdata.processId",
        "ProcessName": "win.eventdata.processName",
        "ProcessPath": "win.eventdata.processPath",
        "Product": "win.eventdata.product",
        "Properties": "win.eventdata.properties",
        "ProviderContextName": "win.evendata.providerContextName",
        "ProviderName": "win.eventdata.providerName",
        "Provider_Name": "win.eventdata.providerName",
        "QueryName": "win.eventdata.queryName",
        "RelativeTargetName": "win.eventdata.relativeTargetName",
        "RemoteAddress": "win.eventdata.remoteAddress",
        "SamAccountName": "win.eventdata.samAccountName",
        "ScriptBlockText": "win.eventdata.scriptBlockText",
        "Service": "win.eventdata.service",
        "ServerName": "win.eventdata.serverName",
        "ServiceFileName": "win.eventdata.serviceFileName",
        "ServiceName": "win.eventdata.serviceName",
        "ServiceStartType": "win.evendata.serviceStartType",
        "ServiceType": "win.evendata.serviceType",
        "sha1": "win.eventdata.hashes",
        "sha256": "win.eventdata.hashes",
        "ShareName": "win.eventdata.shareName",
        "SidHistory": "win.eventdata.sidHistory",
        "Signed": "win.eventdata.signed",
        "Source": "win.eventdata.source",
        "Source_Name": "win.eventdata.sourceName",
        "SourceAddress": "win.eventdata.sourceAddress",
        "SourceImage": "win.eventdata.sourceImage",
        "SourceNetworkAddress": "win.eventdata.ipAddress",
        "SourcePort": "win.eventdata.sourcePort",
        "SourceWorkstation": "win.eventdata.workstation",
        "StartAddress": "win.eventdata.startAddress",
        "StartFunction": "win.eventdata.startFunction",
        "StartModule": "win.eventdata.startModule",
        "State": "win.eventdata.state",
        "Status": "win.eventdata.status",
        "SubcategoryGuid": "win.eventdata.subcategoryGuid",
        "SubjectAccountName": "win.eventdata.subjectUserName",
        "SubjectDomainName": "win.eventdata.subjectDomainName",
        "SubjectLogonId": "win.eventdata.subjectLogonId",
        "SubjectUserName": "win.eventdata.subjectUserName",
        "SubjectUserSid": "win.eventdata.subjectUserSid",
        "Task": "win.eventdata.task",
        "TaskName": "win.eventdata.taskName",
        "TargetFilename": "win.eventdata.targetFilename",
        "TargetImage": "win.eventdata.targetImage",
        "TargetLogonId": "win.eventdata.targetLogonId",
        "TargetName": "win.eventdata.targetName",
        "TargetObject": "win.eventdata.targetObject",
        "TargetOutboundUserName": "win.eventdata.targetOutboundUserName",
        "TargetProcessAddress": "win.eventdata.targetProcessAddress",
        "TargetServerName": "win.eventdata.targetServerName",
        "TargetSid": "win.eventdata.targetSid",
        "TargetUserName": "win.eventdata.targetUserName",
        "TargetUserSid": "win.eventdata.targetUserSid",
        "TicketEncryptionType": "win.eventdata.ticketEncryptionType",
        "TicketOptions": "win.eventdata.ticketOptions",
        "Type": "win.eventdata.type",
        "User": "win.eventdata.user",
        "UserName": "win.eventdata.samAccountName",
        "Value": "win.evendata.value",
        "WorkstationName": "win.eventdata.workstationName",
    },

    # ── Windows Defender ──────────────────────────────────────────────────
    "windows_defender": {
        "Action": "win.eventdata.action",
        "ThreatName": "win.eventdata.threatName",
        "Severity": "win.eventdata.severity",
        "Category": "win.eventdata.category",
        "Path": "win.eventdata.path",
        "DetectionUser": "win.eventdata.detectionUser",
        "SignatureVersion": "win.eventdata.signatureVersion",
        "EngineVersion": "win.eventdata.engineVersion",
        "ProductVersion": "win.eventdata.productVersion",
        "ErrorCode": "win.eventdata.errorCode",
        "ErrorDescription": "win.eventdata.errorDescription",
        "FWLink": "win.eventdata.fwLink",
        "ProcessName": "win.eventdata.processName",
        "SecurityIntelligenceVersion": "win.eventdata.securityIntelligenceVersion",
    },

    # ── Zeek (Bro) NSM — fields decoded from JSON logs ───────────────────
    "zeek": {
        "answers": "answers",
        "c-uri": "c-uri",
        "c-useragent": "c-useragent",
        "certificate.serial": "certificate.serial",
        "certificate.subject": "certificate.subject",
        "certificate.issuer": "certificate.issuer",
        "client_header_names": "client_header_names",
        "conn_state": "conn_state",
        "dst_ip": "dstip",
        "dst_port": "dstport",
        "duration": "duration",
        "endpoint": "endpoint",
        "history": "history",
        "id.orig_h": "srcip",
        "id.orig_p": "srcport",
        "id.resp_h": "dstip",
        "id.resp_p": "dstport",
        "info_code": "info_code",
        "info_msg": "info_msg",
        "last_alert": "last_alert",
        "local_orig": "local_orig",
        "local_resp": "local_resp",
        "method": "method",
        "missed_bytes": "missed_bytes",
        "msg": "msg",
        "name": "name",
        "note": "note",
        "operation": "operation",
        "orig_bytes": "orig_bytes",
        "orig_pkts": "orig_pkts",
        "p": "p",
        "path": "path",
        "proto": "proto",
        "qtype_name": "qtype_name",
        "query": "query",
        "rejected": "rejected",
        "request_body_len": "request_body_len",
        "resp_bytes": "resp_bytes",
        "resp_mime_types": "resp_mime_types",
        "resp_pkts": "resp_pkts",
        "rtt": "rtt",
        "server_name": "server_name",
        "service": "service",
        "src": "srcip",
        "src_ip": "srcip",
        "src_port": "srcport",
        "dst": "dstip",
        "status_code": "status_code",
        "sub": "sub",
        "tunnel_parents": "tunnel_parents",
        "uri": "uri",
        "z": "z",
    },

    # ── Linux Audit daemon (auditd) — Wazuh audit.* decoder ──────────────
    "auditd": {
        "exe": "audit.exe",
        "pid": "audit.pid",
        "ppid": "audit.ppid",
        "uid": "audit.uid",
        "auid": "audit.auid",
        "euid": "audit.euid",
        "suid": "audit.suid",
        "fsuid": "audit.fsuid",
        "gid": "audit.gid",
        "egid": "audit.egid",
        "sgid": "audit.sgid",
        "fsgid": "audit.fsgid",
        "success": "audit.success",
        "syscall": "audit.syscall",
        "SYSCALL": "audit.syscall",
        "key": "audit.key",
        "comm": "audit.command",
        "cwd": "audit.directory",
        "name": "audit.file.name",
        "inode": "audit.file.inode",
        "mode": "audit.file.mode",
        "ouid": "audit.file.ouid",
        "ogid": "audit.file.ogid",
        "type": "audit.type",
        "arch": "audit.arch",
        "exit": "audit.exit",
        "a0": "audit.a0",
        "a1": "audit.a1",
        "a2": "audit.a2",
        "a3": "audit.a3",
        "addr": "audit.addr",
        "terminal": "audit.terminal",
        "hostname": "audit.hostname",
        "res": "audit.res",
        "proctitle": "audit.proctitle",
        "dev": "audit.device",
        "msg": "audit.msg",
        "subj": "audit.subj",
        "obj": "audit.obj",
        "acct": "audit.acct",
        "ses": "audit.session",
        "op": "audit.op",
        "tty": "audit.tty",
        "perm": "audit.perm",
        "flags": "audit.flags",
        "items": "audit.items",
        "syscall_name": "audit.syscall",
        "CommandLine": "audit.proctitle",
        "Image": "audit.exe",
        "User": "audit.uid",
        "ProcessId": "audit.pid",
        "ParentProcessId": "audit.ppid",
    },

    # ── Sysmon for Linux — decoded by Wazuh Sysmon for Linux decoder (eventdata.*)
    "sysmon_linux": {
        "Image": "eventdata.image",
        "CommandLine": "eventdata.commandLine",
        "CurrentDirectory": "eventdata.currentDirectory",
        "User": "eventdata.user",
        "Hashes": "eventdata.hashes",
        "md5": "eventdata.hashes",
        "sha1": "eventdata.hashes",
        "sha256": "eventdata.hashes",
        "Imphash": "eventdata.imphash",
        "ParentImage": "eventdata.parentImage",
        "ParentCommandLine": "eventdata.parentCommandLine",
        "ParentUser": "eventdata.parentUser",
        "ProcessId": "eventdata.processId",
        "ProcessGuid": "eventdata.processGuid",
        "ParentProcessId": "eventdata.parentProcessId",
        "ParentProcessGuid": "eventdata.parentProcessGuid",
        "TargetFilename": "eventdata.targetFilename",
        "CreationUtcTime": "eventdata.creationUtcTime",
        "PreviousCreationUtcTime": "eventdata.previousCreationUtcTime",
        "DestinationIp": "eventdata.destinationIp",
        "DestinationPort": "eventdata.destinationPort",
        "DestinationHostname": "eventdata.destinationHostname",
        "SourceIp": "eventdata.sourceIp",
        "SourcePort": "eventdata.sourcePort",
        "SourceHostname": "eventdata.sourceHostname",
        "Protocol": "eventdata.protocol",
        "Initiated": "eventdata.initiated",
        "ImageLoaded": "eventdata.imageLoaded",
        "Signed": "eventdata.signed",
        "Signature": "eventdata.signature",
        "SignatureStatus": "eventdata.signatureStatus",
        "PipeName": "eventdata.pipeName",
        "SourceImage": "eventdata.sourceImage",
        "TargetImage": "eventdata.targetImage",
        "GrantedAccess": "eventdata.grantedAccess",
        "CallTrace": "eventdata.callTrace",
        "TargetObject": "eventdata.targetObject",
        "Details": "eventdata.details",
        "EventType": "eventdata.eventType",
        "Device": "eventdata.device",
        "RuleName": "eventdata.ruleName",
        "IntegrityLevel": "eventdata.integrityLevel",
        "LogonId": "eventdata.logonId",
        "LogonGuid": "eventdata.logonGuid",
        "TerminalSessionId": "eventdata.terminalSessionId",
        "Description": "eventdata.description",
        "Product": "eventdata.product",
        "Company": "eventdata.company",
        "OriginalFileName": "eventdata.originalFileName",
        "FileVersion": "eventdata.fileVersion",
    },

    # ── Generic Linux — process fields via Sysmon for Linux (eventdata.*)
    # Low-level kernel/syslog fields mapped to auditd paths.
    "linux": {
        # Process execution (Sysmon for Linux → eventdata.*)
        "Image": "eventdata.image",
        "CommandLine": "eventdata.commandLine",
        "CurrentDirectory": "eventdata.currentDirectory",
        "User": "eventdata.user",
        "ParentImage": "eventdata.parentImage",
        "ParentCommandLine": "eventdata.parentCommandLine",
        "ParentUser": "eventdata.parentUser",
        "ProcessId": "eventdata.processId",
        "ParentProcessId": "eventdata.parentProcessId",
        "ProcessGuid": "eventdata.processGuid",
        "ParentProcessGuid": "eventdata.parentProcessGuid",
        "IntegrityLevel": "eventdata.integrityLevel",
        # File events
        "TargetFilename": "eventdata.targetFilename",
        "CreationUtcTime": "eventdata.creationUtcTime",
        # Network events
        "DestinationIp": "eventdata.destinationIp",
        "DestinationPort": "eventdata.destinationPort",
        "DestinationHostname": "eventdata.destinationHostname",
        "SourceIp": "eventdata.sourceIp",
        "SourcePort": "eventdata.sourcePort",
        "Protocol": "eventdata.protocol",
        "Initiated": "eventdata.initiated",
        # Hashes
        "Hashes": "eventdata.hashes",
        "md5": "eventdata.hashes",
        "sha1": "eventdata.hashes",
        "sha256": "eventdata.hashes",
        # Generic kernel / syslog / auditd fields
        "exe": "audit.exe",
        "comm": "audit.command",
        "uid": "uid",
        "gid": "gid",
        "pid": "pid",
        "ppid": "ppid",
        "tty": "tty",
        "cwd": "cwd",
        "name": "name",
        "path": "path",
        "Hostname": "hostname",
        "msg": "full_log",
    },

    # ── PAM (Pluggable Authentication Modules) ───────────────────────────
    "pam": {
        "User": "dstuser",
        "uid": "uid",
        "Service": "program_name",
        "Hostname": "srcip",
        "rhost": "srcip",
        "tty": "tty",
        "msg": "full_log",
        "error": "error",
    },

    # ── SSH ───────────────────────────────────────────────────────────────
    "ssh": {
        "User": "dstuser",
        "src_ip": "srcip",
        "dst_ip": "dstip",
        "src_port": "srcport",
        "dst_port": "dstport",
        "method": "ssh_method",
        "protocol": "protocol",
        "Hostname": "srcip",
        "rhost": "srcip",
        "laddr": "dstip",
        "lport": "dstport",
        "key_fingerprint": "ssh_key",
        "error_msg": "error",
        "msg": "full_log",
    },

    # ── Sudo ─────────────────────────────────────────────────────────────
    "sudo": {
        "User": "srcuser",
        "RunAsUser": "dstuser",
        "Command": "command",
        "Tty": "tty",
        "Cwd": "cwd",
        "Host": "hostname",
        "msg": "full_log",
    },

    # ── ClamAV ───────────────────────────────────────────────────────────
    "clamav": {
        "file": "virname",
        "virus": "virname",
        "action": "action",
        "msg": "full_log",
    },

    # ── Apache HTTP Server ────────────────────────────────────────────────
    "apache": {
        "c-ip": "srcip",
        "cs-uri": "url",
        "cs-uri-stem": "url",
        "cs-uri-query": "url",
        "sc-status": "id",
        "cs-method": "request_method",
        "cs-User-Agent": "browser",
        "cs-Referer": "http_refer",
        "s-ip": "dstip",
        "s-port": "dstport",
        "cs-host": "hostname",
        "time-taken": "time",
        "sc-bytes": "bytes",
        "cs-bytes": "req_bytes",
        "cs-version": "protocol",
        "cs-username": "srcuser",
        "c-port": "srcport",
        "cs-cookie": "cookie",
        "cs(User-Agent)": "browser",
        "cs(Referer)": "http_refer",
        "cs(Cookie)": "cookie",
        "RequestMethod": "request_method",
        "RequestPath": "url",
        "StatusCode": "id",
        "UserAgent": "browser",
        "RemoteIP": "srcip",
    },

    # ── Nginx ─────────────────────────────────────────────────────────────
    "nginx": {
        "c-ip": "srcip",
        "remote_addr": "srcip",
        "request": "url",
        "request_uri": "url",
        "uri": "url",
        "status": "id",
        "request_method": "request_method",
        "http_user_agent": "browser",
        "http_referer": "http_refer",
        "server_name": "hostname",
        "server_port": "dstport",
        "bytes_sent": "bytes",
        "body_bytes_sent": "bytes",
        "request_length": "req_bytes",
        "http_x_forwarded_for": "http_x_forwarded_for",
        "upstream_addr": "dstip",
        "upstream_status": "upstream_status",
        "upstream_response_time": "upstream_response_time",
        "request_time": "time",
        "ssl_protocol": "protocol",
        "ssl_cipher": "ssl_cipher",
    },

    # ── IIS (Internet Information Services) ──────────────────────────────
    "iis": {
        "c-ip": "srcip",
        "cs-uri-stem": "url",
        "cs-uri-query": "url",
        "sc-status": "id",
        "sc-substatus": "id",
        "sc-win32-status": "win32_status",
        "cs-method": "request_method",
        "cs(User-Agent)": "browser",
        "cs(Referer)": "http_refer",
        "s-ip": "dstip",
        "s-port": "dstport",
        "cs-host": "hostname",
        "cs-username": "srcuser",
        "time-taken": "time",
        "sc-bytes": "bytes",
        "cs-bytes": "req_bytes",
        "cs-version": "protocol",
        "cs(Cookie)": "cookie",
        "c-port": "srcport",
    },

    # ── AWS CloudTrail ────────────────────────────────────────────────────
    "aws": {
        "eventName": "aws.eventName",
        "eventSource": "aws.eventSource",
        "eventType": "aws.eventType",
        "awsRegion": "aws.awsRegion",
        "sourceIPAddress": "aws.sourceIPAddress",
        "userAgent": "aws.userAgent",
        "errorCode": "aws.errorCode",
        "errorMessage": "aws.errorMessage",
        "readOnly": "aws.readOnly",
        "managementEvent": "aws.managementEvent",
        "recipientAccountId": "aws.recipientAccountId",
        "userIdentity.type": "aws.userIdentity.type",
        "userIdentity.arn": "aws.userIdentity.arn",
        "userIdentity.accountId": "aws.userIdentity.accountId",
        "userIdentity.principalId": "aws.userIdentity.principalId",
        "userIdentity.userName": "aws.userIdentity.userName",
        "userIdentity.sessionContext.sessionIssuer.userName": "aws.userIdentity.sessionContext.sessionIssuer.userName",
        "userIdentity.sessionContext.sessionIssuer.arn": "aws.userIdentity.sessionContext.sessionIssuer.arn",
        "userIdentity.sessionContext.sessionIssuer.type": "aws.userIdentity.sessionContext.sessionIssuer.type",
        "userIdentity.invokedBy": "aws.userIdentity.invokedBy",
        "requestParameters.bucketName": "aws.requestParameters.bucketName",
        "requestParameters.keyName": "aws.requestParameters.keyName",
        "requestParameters.tableName": "aws.requestParameters.tableName",
        "requestParameters.functionName": "aws.requestParameters.functionName",
        "requestParameters.roleName": "aws.requestParameters.roleName",
        "requestParameters.userName": "aws.requestParameters.userName",
        "requestParameters.groupName": "aws.requestParameters.groupName",
        "requestParameters.policyName": "aws.requestParameters.policyName",
        "requestParameters.policyDocument": "aws.requestParameters.policyDocument",
        "requestParameters.instanceId": "aws.requestParameters.instanceId",
        "requestParameters.imageId": "aws.requestParameters.imageId",
        "requestParameters.stackName": "aws.requestParameters.stackName",
        "requestParameters.clusterName": "aws.requestParameters.clusterName",
        "requestParameters.resourceArn": "aws.requestParameters.resourceArn",
        "resources.ARN": "aws.resources.ARN",
        "resources.type": "aws.resources.type",
        "responseElements.instanceId": "aws.responseElements.instanceId",
        "responseElements.publicDnsName": "aws.responseElements.publicDnsName",
        "responseElements.functionArn": "aws.responseElements.functionArn",
        "responseElements.ConsoleLogin": "aws.responseElements.ConsoleLogin",
        "additionalEventData.mfaUsed": "aws.additionalEventData.mfaUsed",
        "additionalEventData.MFAUsed": "aws.additionalEventData.MFAUsed",
        "additionalEventData.loginTo": "aws.additionalEventData.loginTo",
    },

    # ── Microsoft Azure Activity Logs / Azure AD ──────────────────────────
    "azure": {
        "operationName": "azure.operationName",
        "Operation": "azure.operationName",
        "resultType": "azure.resultType",
        "ResultType": "azure.resultType",
        "resultDescription": "azure.resultDescription",
        "callerIpAddress": "azure.callerIpAddress",
        "correlationId": "azure.correlationId",
        "level": "azure.level",
        "resourceType": "azure.resourceType",
        "resourceGroup": "azure.resourceGroup",
        "resourceProvider": "azure.resourceProvider",
        "subscriptionId": "azure.subscriptionId",
        "Workload": "azure.properties.Workload",
        "ActivityDisplayName": "azure.properties.activityDisplayName",
        "Category": "azure.properties.category",
        "Result": "azure.properties.result",
        "ResultDescription": "azure.properties.resultDescription",
        "LoggedByService": "azure.properties.loggedByService",
        "InitiatedByUser": "azure.properties.initiatedBy.user.userPrincipalName",
        "InitiatedByUserIP": "azure.properties.initiatedBy.user.ipAddress",
        "InitiatedByApp": "azure.properties.initiatedBy.app.displayName",
        "TargetResourceDisplayName": "azure.properties.targetResources.displayName",
        "TargetResourceType": "azure.properties.targetResources.type",
        "TargetResourceUserPrincipalName": "azure.properties.targetResources.userPrincipalName",
        "TargetResourceModifiedProperty": "azure.properties.targetResources.modifiedProperties.displayName",
        "ModifiedProperties": "azure.properties.targetResources.modifiedProperties.newValue",
        "UserPrincipalName": "azure.properties.initiatedBy.user.userPrincipalName",
        "IPAddress": "azure.callerIpAddress",
        "UserAgent": "azure.userAgent",
        "ConditionalAccessStatus": "azure.properties.conditionalAccessStatus",
        "AuthenticationRequirement": "azure.properties.authenticationRequirement",
        "ClientAppUsed": "azure.properties.clientAppUsed",
        "AppDisplayName": "azure.properties.appDisplayName",
        "ResourceDisplayName": "azure.properties.resourceDisplayName",
        "IsInteractive": "azure.properties.isInteractive",
        "RiskState": "azure.properties.riskState",
        "RiskLevelAggregated": "azure.properties.riskLevelAggregated",
        "RiskDetail": "azure.properties.riskDetail",
        "DetectedRiskTypes": "azure.properties.detectedRiskTypes",
        "Location": "azure.properties.location.city",
        "CountryOrRegion": "azure.properties.location.countryOrRegion",
        "properties.message": "azure.properties.message",
    },

    # ── Google Cloud Platform (GCP) Audit Logs ────────────────────────────
    "gcp": {
        "methodName": "gcp.protoPayload.methodName",
        "serviceName": "gcp.protoPayload.serviceName",
        "resourceName": "gcp.protoPayload.resourceName",
        "callerIp": "gcp.protoPayload.requestMetadata.callerIp",
        "callerSuppliedUserAgent": "gcp.protoPayload.requestMetadata.callerSuppliedUserAgent",
        "authenticationInfo.principalEmail": "gcp.protoPayload.authenticationInfo.principalEmail",
        "authorizationInfo.resource": "gcp.protoPayload.authorizationInfo.resource",
        "authorizationInfo.permission": "gcp.protoPayload.authorizationInfo.permission",
        "authorizationInfo.granted": "gcp.protoPayload.authorizationInfo.granted",
        "requestMetadata.callerIp": "gcp.protoPayload.requestMetadata.callerIp",
        "status.code": "gcp.protoPayload.status.code",
        "status.message": "gcp.protoPayload.status.message",
        "resource.type": "gcp.resource.type",
        "resource.labels.project_id": "gcp.resource.labels.project_id",
        "resource.labels.zone": "gcp.resource.labels.zone",
        "resource.labels.instance_id": "gcp.resource.labels.instance_id",
        "severity": "gcp.severity",
        "logName": "gcp.logName",
        "insertId": "gcp.insertId",
        "principalEmail": "gcp.protoPayload.authenticationInfo.principalEmail",
        "callerType": "gcp.protoPayload.authenticationInfo.callerType",
        "projectId": "gcp.resource.labels.project_id",
    },

    # ── Microsoft Office 365 Unified Audit Log ────────────────────────────
    "office365": {
        "Operation": "office365.Operation",
        "UserId": "office365.UserId",
        "ClientIP": "office365.ClientIP",
        "ResultStatus": "office365.ResultStatus",
        "Workload": "office365.Workload",
        "RecordType": "office365.RecordType",
        "UserAgent": "office365.UserAgent",
        "UserType": "office365.UserType",
        "ObjectId": "office365.ObjectId",
        "Site": "office365.Site",
        "SiteUrl": "office365.SiteUrl",
        "SourceFileName": "office365.SourceFileName",
        "DestinationFileName": "office365.DestinationFileName",
        "SourceRelativeUrl": "office365.SourceRelativeUrl",
        "DestinationRelativeUrl": "office365.DestinationRelativeUrl",
        "ListId": "office365.ListId",
        "ListItemUniqueId": "office365.ListItemUniqueId",
        "FileSize": "office365.FileSize",
        "UserKey": "office365.UserKey",
        "TeamName": "office365.TeamName",
        "ChannelName": "office365.ChannelName",
        "MessageId": "office365.MessageId",
        "CommunicationType": "office365.CommunicationType",
        "AppId": "office365.AppId",
        "AppName": "office365.AppName",
        "ClientIPAddress": "office365.ClientIP",
        "MailboxOwnerUPN": "office365.MailboxOwnerUPN",
        "LogonType": "office365.LogonType",
        "MailboxGuid": "office365.MailboxGuid",
        "Folder": "office365.Folder",
        "AffectedItems": "office365.AffectedItems",
        "Subject": "office365.Subject",
        "InternetMessageId": "office365.InternetMessageId",
        "SenderAddress": "office365.SenderAddress",
        "RecipientAddress": "office365.RecipientAddress",
        "AttachmentData": "office365.AttachmentData",
        "PolicyName": "office365.PolicyName",
        "PolicyAction": "office365.PolicyAction",
        "SensitiveInfoDetectionIsIncluded": "office365.SensitiveInfoDetectionIsIncluded",
        "AuthenticationMethod": "office365.AuthenticationMethod",
    },

    # ── Okta Identity Platform ────────────────────────────────────────────
    "okta": {
        "eventType": "okta.eventType",
        "displayMessage": "okta.displayMessage",
        "severity": "okta.severity",
        "actor.id": "okta.actor.id",
        "actor.type": "okta.actor.type",
        "actor.alternateId": "okta.actor.alternateId",
        "actor.displayName": "okta.actor.displayName",
        "client.ipAddress": "okta.client.ipAddress",
        "client.userAgent.rawUserAgent": "okta.client.userAgent.rawUserAgent",
        "client.userAgent.browser": "okta.client.userAgent.browser",
        "client.userAgent.os": "okta.client.userAgent.os",
        "client.geographicalContext.city": "okta.client.geographicalContext.city",
        "client.geographicalContext.country": "okta.client.geographicalContext.country",
        "outcome.result": "okta.outcome.result",
        "outcome.reason": "okta.outcome.reason",
        "target.id": "okta.target.id",
        "target.type": "okta.target.type",
        "target.alternateId": "okta.target.alternateId",
        "target.displayName": "okta.target.displayName",
        "authenticationContext.authenticationStep": "okta.authenticationContext.authenticationStep",
        "authenticationContext.externalSessionId": "okta.authenticationContext.externalSessionId",
        "securityContext.isTorTraffic": "okta.securityContext.isTorTraffic",
        "securityContext.isProxy": "okta.securityContext.isProxy",
        "securityContext.isp": "okta.securityContext.isp",
        "transaction.id": "okta.transaction.id",
        "transaction.type": "okta.transaction.type",
        "UserAgent": "okta.client.userAgent.rawUserAgent",
        "IPAddress": "okta.client.ipAddress",
        "EventType": "okta.eventType",
        "User": "okta.actor.alternateId",
        "Result": "okta.outcome.result",
    },

    # ── GitHub Audit Logs ─────────────────────────────────────────────────
    "github": {
        "action": "github.action",
        "actor": "github.actor",
        "actor_ip": "github.actor_ip",
        "user": "github.user",
        "repo": "github.repo",
        "org": "github.org",
        "team": "github.team",
        "repository": "github.repo",
        "repository_public": "github.repository_public",
        "visibility": "github.visibility",
        "config.url": "github.config.url",
        "events": "github.events",
        "hook_id": "github.hook_id",
        "deployment_id": "github.deployment_id",
        "environment": "github.environment",
        "head_branch": "github.head_branch",
        "head_sha": "github.head_sha",
        "data.key": "github.data.key",
        "key_id": "github.key_id",
        "limited_availability": "github.limited_availability",
        "permission": "github.permission",
        "workflow_id": "github.workflow_id",
        "workflow_run_id": "github.workflow_run_id",
        "name": "github.name",
        "business": "github.business",
        "external_identity_nameid": "github.external_identity_nameid",
        "saml_configuration_url": "github.saml_configuration_url",
        "target_login": "github.target_login",
        "transport_protocol_name": "github.transport_protocol_name",
    },

    # ── Kubernetes (k8s API server audit log) ────────────────────────────
    "kubernetes": {
        "verb": "kubernetes.verb",
        "requestURI": "kubernetes.requestURI",
        "apiVersion": "kubernetes.apiVersion",
        "objectRef.resource": "kubernetes.objectRef.resource",
        "objectRef.namespace": "kubernetes.objectRef.namespace",
        "objectRef.name": "kubernetes.objectRef.name",
        "objectRef.apiGroup": "kubernetes.objectRef.apiGroup",
        "objectRef.apiVersion": "kubernetes.objectRef.apiVersion",
        "objectRef.subresource": "kubernetes.objectRef.subresource",
        "user.username": "kubernetes.user.username",
        "user.uid": "kubernetes.user.uid",
        "user.groups": "kubernetes.user.groups",
        "sourceIPs": "kubernetes.sourceIPs",
        "userAgent": "kubernetes.userAgent",
        "responseStatus.code": "kubernetes.responseStatus.code",
        "responseStatus.message": "kubernetes.responseStatus.message",
        "responseStatus.reason": "kubernetes.responseStatus.reason",
        "requestObject.metadata.name": "kubernetes.requestObject.metadata.name",
        "requestObject.spec.containers.image": "kubernetes.requestObject.spec.containers.image",
        "requestObject.spec.containers.name": "kubernetes.requestObject.spec.containers.name",
        "requestObject.spec.serviceAccountName": "kubernetes.requestObject.spec.serviceAccountName",
        "requestObject.spec.hostNetwork": "kubernetes.requestObject.spec.hostNetwork",
        "requestObject.spec.hostPID": "kubernetes.requestObject.spec.hostPID",
        "requestObject.spec.hostIPC": "kubernetes.requestObject.spec.hostIPC",
        "requestObject.spec.privileged": "kubernetes.requestObject.spec.privileged",
        "requestObject.rules.verbs": "kubernetes.requestObject.rules.verbs",
        "requestObject.rules.resources": "kubernetes.requestObject.rules.resources",
        "annotations.authorization.k8s.io/decision": "kubernetes.annotations.authorization_k8s_io_decision",
        "annotations.authorization.k8s.io/reason": "kubernetes.annotations.authorization_k8s_io_reason",
        "User": "kubernetes.user.username",
        "IPAddress": "kubernetes.sourceIPs",
        "Resource": "kubernetes.objectRef.resource",
        "Namespace": "kubernetes.objectRef.namespace",
        "Image": "kubernetes.requestObject.spec.containers.image",
    },

    # ── DNS (generic — Wazuh dns decoder) ────────────────────────────────
    "dns": {
        "QueryName": "dns.question.name",
        "QueryType": "dns.question.type",
        "QueryResults": "dns.answer.rdata",
        "record_type": "dns.question.type",
        "answer": "dns.answer.rdata",
        "query": "dns.question.name",
        "src_ip": "srcip",
        "dst_ip": "dstip",
        "src_port": "srcport",
        "dst_port": "dstport",
        "protocol": "protocol",
        "response_code": "dns.response_code",
        "flags": "dns.flags",
        "ttl": "dns.answer.ttl",
        "id": "dns.id",
        "transaction_id": "dns.id",
        "rx_bytes": "dns.bytes_received",
        "tx_bytes": "dns.bytes_sent",
    },

    # ── Network (generic / firewall) ──────────────────────────────────────
    "network": {
        "src_ip": "srcip",
        "dst_ip": "dstip",
        "src_port": "srcport",
        "dst_port": "dstport",
        "protocol": "protocol",
        "proto": "protocol",
        "action": "action",
        "Action": "action",
        "bytes_in": "bytes_in",
        "bytes_out": "bytes_out",
        "packets_in": "packets_in",
        "packets_out": "packets_out",
        "interface": "interface",
        "direction": "direction",
        "Direction": "direction",
        "SourceIp": "srcip",
        "DestinationIp": "dstip",
        "SourceAddress": "srcip",
        "DestinationAddress": "dstip",
        "SourcePort": "srcport",
        "DestinationPort": "dstport",
        "Protocol": "protocol",
        "Network": "network",
        "Community_ID": "community_id",
        "network.transport": "protocol",
        "network.application": "network_app",
        "rule_name": "rule_name",
        "RuleName": "rule_name",
        "Initiated": "direction",
        "DeviceName": "hostname",
        "SourceUser": "srcuser",
        "DestinationUser": "dstuser",
        "Bytes": "bytes",
        "BytesIn": "bytes_in",
        "BytesOut": "bytes_out",
        "EventID": "id",
    },

    # ── Palo Alto Networks PAN-OS ─────────────────────────────────────────
    "palo_alto": {
        "Action": "action",
        "SourceIP": "srcip",
        "DestinationIP": "dstip",
        "SourceAddress": "srcip",
        "DestinationAddress": "dstip",
        "src_ip": "srcip",
        "dst_ip": "dstip",
        "SourcePort": "srcport",
        "DestinationPort": "dstport",
        "src_port": "srcport",
        "dst_port": "dstport",
        "Protocol": "protocol",
        "proto": "protocol",
        "Application": "pan.app",
        "app": "pan.app",
        "Rule": "pan.rule",
        "RuleName": "pan.rule",
        "URLCategory": "pan.category",
        "Category": "pan.category",
        "url_category": "pan.category",
        "ThreatID": "pan.threat_id",
        "ThreatName": "pan.threat_name",
        "SubType": "pan.subtype",
        "Subtype": "pan.subtype",
        "subtype": "pan.subtype",
        "Type": "pan.type",
        "type": "pan.type",
        "SourceUser": "srcuser",
        "DestinationUser": "dstuser",
        "srcuser": "srcuser",
        "dstuser": "dstuser",
        "SourceZone": "pan.src_zone",
        "DestinationZone": "pan.dst_zone",
        "src_zone": "pan.src_zone",
        "dst_zone": "pan.dst_zone",
        "Direction": "pan.direction",
        "direction": "pan.direction",
        "SessionEndReason": "pan.session_end_reason",
        "Severity": "pan.severity",
        "DeviceName": "pan.device_name",
        "VirtualSystem": "pan.vsys",
        "NATSourceIP": "pan.nat_srcip",
        "NATDestinationIP": "pan.nat_dstip",
        "NATSourcePort": "pan.nat_srcport",
        "NATDestinationPort": "pan.nat_dstport",
        "FileName": "pan.filename",
        "FileType": "pan.filetype",
        "Bytes": "bytes",
        "BytesIn": "bytes_in",
        "BytesOut": "bytes_out",
        "Flags": "pan.flags",
        "LogSubtype": "pan.subtype",
        "EventCode": "pan.event_code",
        "HTTPMethod": "request_method",
        "SourceLocation": "pan.src_location",
        "DestinationLocation": "pan.dst_location",
        "Community_ID": "community_id",
    },

    # ── Cisco ASA / FTD / IOS ─────────────────────────────────────────────
    "cisco": {
        "SourceIp": "srcip",
        "DestinationIp": "dstip",
        "SourceAddress": "srcip",
        "DestinationAddress": "dstip",
        "src_ip": "srcip",
        "dst_ip": "dstip",
        "SourcePort": "srcport",
        "DestinationPort": "dstport",
        "src_port": "srcport",
        "dst_port": "dstport",
        "Protocol": "protocol",
        "proto": "protocol",
        "Action": "action",
        "action": "action",
        "SID": "id",
        "DeviceEventClassID": "id",
        "EventID": "id",
        "Reason": "cisco.reason",
        "Direction": "direction",
        "Interface": "interface",
        "SourceInterface": "cisco.src_interface",
        "DestinationInterface": "cisco.dst_interface",
        "SourceUser": "srcuser",
        "DestinationUser": "dstuser",
        "Category": "cisco.category",
        "Severity": "cisco.severity",
        "DeviceName": "hostname",
        "NATSourceIP": "cisco.nat_srcip",
        "NATDestinationIP": "cisco.nat_dstip",
        "NATSourcePort": "cisco.nat_srcport",
        "NATDestinationPort": "cisco.nat_dstport",
        "Message": "full_log",
        "msg": "full_log",
    },

    # ── Fortinet FortiGate ────────────────────────────────────────────────
    "fortinet": {
        "srcip": "srcip",
        "dstip": "dstip",
        "src_ip": "srcip",
        "dst_ip": "dstip",
        "SourceIp": "srcip",
        "DestinationIp": "dstip",
        "srcport": "srcport",
        "dstport": "dstport",
        "src_port": "srcport",
        "dst_port": "dstport",
        "SourcePort": "srcport",
        "DestinationPort": "dstport",
        "proto": "protocol",
        "Protocol": "protocol",
        "action": "action",
        "Action": "action",
        "policyname": "fortinet.policyname",
        "policyid": "fortinet.policyid",
        "type": "fortinet.type",
        "subtype": "fortinet.subtype",
        "srcintf": "fortinet.srcintf",
        "dstintf": "fortinet.dstintf",
        "user": "srcuser",
        "srcuser": "srcuser",
        "dstuser": "dstuser",
        "app": "fortinet.app",
        "appcat": "fortinet.appcat",
        "service": "fortinet.service",
        "reason": "fortinet.reason",
        "devname": "fortinet.devname",
        "vd": "fortinet.vd",
        "status": "fortinet.status",
        "threattype": "fortinet.threattype",
        "level": "fortinet.level",
        "logid": "fortinet.logid",
        "logdesc": "fortinet.logdesc",
        "cfgpath": "fortinet.cfgpath",
        "cfgattr": "fortinet.cfgattr",
        "cfgobj": "fortinet.cfgobj",
        "direction": "direction",
        "Direction": "direction",
        "Category": "fortinet.category",
        "urlcat": "fortinet.category",
        "AttackName": "fortinet.attack_name",
        "msg": "full_log",
        "message": "full_log",
    },

    # ── Check Point ───────────────────────────────────────────────────────
    "checkpoint": {
        "src": "srcip",
        "dst": "dstip",
        "src_ip": "srcip",
        "dst_ip": "dstip",
        "SourceAddress": "srcip",
        "DestinationAddress": "dstip",
        "SourceIp": "srcip",
        "DestinationIp": "dstip",
        "service": "dstport",
        "src_port": "srcport",
        "dst_port": "dstport",
        "SourcePort": "srcport",
        "DestinationPort": "dstport",
        "proto": "protocol",
        "Protocol": "protocol",
        "action": "action",
        "Action": "action",
        "rule_name": "checkpoint.rule_name",
        "RuleName": "checkpoint.rule_name",
        "rule_uid": "checkpoint.rule_uid",
        "blade": "checkpoint.blade",
        "product": "checkpoint.product",
        "origin": "checkpoint.origin",
        "severity": "checkpoint.severity",
        "Severity": "checkpoint.severity",
        "conn_direction": "direction",
        "direction": "direction",
        "ifdir": "checkpoint.ifdir",
        "ifname": "checkpoint.ifname",
        "AppID": "checkpoint.appid",
        "AppName": "checkpoint.appname",
        "xlatedst": "checkpoint.xlatedst",
        "xlatesrc": "checkpoint.xlatesrc",
        "xlatedport": "checkpoint.xlatedport",
        "xlatesport": "checkpoint.xlatesport",
        "MatchedBy": "checkpoint.matched_by",
        "loguid": "checkpoint.loguid",
        "Description": "checkpoint.description",
        "src_user_name": "srcuser",
        "user": "srcuser",
        "Category": "checkpoint.category",
        "UrlCategory": "checkpoint.url_category",
        "msg": "full_log",
    },

    # ── OSQuery ───────────────────────────────────────────────────────────
    "osquery": {
        "name": "osquery.name",
        "action": "osquery.action",
        "columns.cmdline": "osquery.columns.cmdline",
        "columns.name": "osquery.columns.name",
        "columns.path": "osquery.columns.path",
        "columns.pid": "osquery.columns.pid",
        "columns.parent": "osquery.columns.parent",
        "columns.uid": "osquery.columns.uid",
        "columns.gid": "osquery.columns.gid",
        "columns.sha256": "osquery.columns.sha256",
        "columns.sha1": "osquery.columns.sha1",
        "columns.md5": "osquery.columns.md5",
        "columns.target_path": "osquery.columns.target_path",
        "columns.category": "osquery.columns.category",
        "columns.username": "osquery.columns.username",
        "columns.groupname": "osquery.columns.groupname",
        "columns.host": "osquery.columns.host",
        "columns.local_address": "osquery.columns.local_address",
        "columns.local_port": "osquery.columns.local_port",
        "columns.remote_address": "osquery.columns.remote_address",
        "columns.remote_port": "osquery.columns.remote_port",
        "columns.protocol": "osquery.columns.protocol",
        "columns.state": "osquery.columns.state",
        "columns.net_namespace": "osquery.columns.net_namespace",
        "columns.socket": "osquery.columns.socket",
        "columns.key": "osquery.columns.key",
        "columns.value": "osquery.columns.value",
        "columns.mtime": "osquery.columns.mtime",
        "columns.inode": "osquery.columns.inode",
        "columns.type": "osquery.columns.type",
        "columns.message": "osquery.columns.message",
        "columns.severity": "osquery.columns.severity",
        "columns.facility": "osquery.columns.facility",
        "columns.source": "osquery.columns.source",
        "columns.destination": "osquery.columns.destination",
    },
}

# Product aliases — normalized before lookup
PRODUCT_ALIASES: Dict[str, str] = {
    # Windows
    "windows_defender": "windows_defender",
    "windefend": "windows_defender",
    "microsoft windows defender": "windows_defender",
    # Linux / Sysmon for Linux
    "sysmonforlinux": "sysmon_linux",
    "sysmon-linux": "sysmon_linux",
    "sysmon_for_linux": "sysmon_linux",
    # Web servers
    "apache-httpd": "apache",
    "apache2": "apache",
    "httpd": "apache",
    # Cloud / SaaS
    "azuread": "azure",
    "azure_ad": "azure",
    "aad": "azure",
    "o365": "office365",
    "m365": "office365",
    "microsoft365": "office365",
    "ms365": "office365",
    "gworkspace": "gcp",
    "googleworkspace": "gcp",
    # Network monitoring
    "bro": "zeek",
    # Orchestration
    "k8s": "kubernetes",
    "kube": "kubernetes",
    # Network / Firewall — generic
    "firewall": "network",
    # Palo Alto Networks
    "palo-alto": "palo_alto",
    "pan-os": "palo_alto",
    "panos": "palo_alto",
    "pan_os": "palo_alto",
    "paloalto": "palo_alto",
    # Cisco
    "cisco-asa": "cisco",
    "cisco-ftd": "cisco",
    "cisco-ios": "cisco",
    "cisco_asa": "cisco",
    "cisco_ftd": "cisco",
    "cisco_ios": "cisco",
    "cisco-nx-os": "cisco",
    "cisco-fwsm": "cisco",
    "cisco-wsa": "cisco",
    # Fortinet
    "fortigate": "fortinet",
    "fortigate-firewall": "fortinet",
    "fortios": "fortinet",
    # Check Point
    "checkpoint-fw": "checkpoint",
    "check-point": "checkpoint",
    # Other common firewalls → generic network
    "sonicwall": "network",
    "pfsense": "network",
    "pfSense": "network",
    "juniper": "network",
    "juniper-junos": "network",
    "junos": "network",
    "f5-big-ip": "network",
    "f5": "network",
    "barracuda": "network",
    "stormshield": "network",
    "meraki": "network",
}


def normalize_product(product: str) -> str:
    """Normalize a product name to its canonical form."""
    p = product.lower().strip()
    return PRODUCT_ALIASES.get(p, p)


def get_field_name(
    product: str,
    field: str,
    overrides: Optional[Dict[str, Dict[str, str]]] = None,
) -> str:
    """
    Resolve a Sigma field name to a Wazuh decoder path.

    Priority:
      1. Session overrides  (per-product, passed via ConversionConfig)
      2. Built-in FIELD_MAPS for the normalized product
      3. Fallback → full_log
    """
    p = normalize_product(product)

    # 1. Session overrides
    if overrides:
        prod_ovr = overrides.get(p) or overrides.get(product.lower())
        if prod_ovr and field in prod_ovr:
            return prod_ovr[field]

    # 2. Built-in map
    maps = FIELD_MAPS.get(p)
    if maps and field in maps:
        return maps[field]

    # 3. Fallback
    return "full_log"


def list_products() -> list[str]:
    """Return all supported product names (canonical + aliases)."""
    return sorted(set(list(FIELD_MAPS.keys()) + list(PRODUCT_ALIASES.keys())))
